Change jshint to eslint
project-hatohol/hatohol pull request #2559
Opened 2017-06-23 05:40 UTC by otakuto

es6対応のためeslintに切り替えました.

2017-06-30 04:07 UTC, masa0612 commented
対応ありがとうございます。
Travisの結果を見るに，チェックは正常に動いているように見えます。
しかしwarningだけでもexit codeが1となり，その時点でテストが終了しています。

「warningを全て修正するか」「warningではexit codeは1にはならない」のどちらかが必要な対処となりますが，
前者はwarningの数が2000弱であまり現実的ではないので，後者の修正をお願いできませんか？

2017-06-30 04:13 UTC, cosmo0920 requested changes

2017-06-30 04:13 UTC, cosmo0920 commented on test/run-client-test.sh
> +npm run lint || FAILED=1
`|| FAILED=1` を消すか、`.eslintrc.yml` に現状のコードでも警告が出ない設定をTODOやFIXMEのコメントとともに入れるのはどうでしょうか？

2017-06-30 04:21 UTC, masa0612 commented on test/run-client-test.sh
> +npm run lint || FAILED=1
これ`|| FIALED=1`を消しちゃうと，先ほどとは反対にerrorが出てもテスト続きますよねたぶん？
それはそれで望ましくない気がするんですが，そこはポリシー次第なんでしょうか

2017-06-30 04:28 UTC, cosmo0920 commented on test/run-client-test.sh
> +npm run lint || FAILED=1
確かに `|| FAILED=1` を消すのは良くなさそうですね。 `.eslintrc.yml` をもうちょっとこねこねする方向の方が良さそう

2017-06-30 07:52 UTC, masa0612 commented
これテストコケてるのってこのPRのせいじゃない。このPR自体問題なさそうだから，aコミット削除して再度PRお願いします。

2017-07-03 01:41 UTC, merged

2017-07-03 02:04 UTC, cosmo0920 commented
:tada: